server:
  port: 8088
spring:
  devtools:
    enabled: ture
  redis:
    host: 192.168.193.141
    port: 6379
    database: 0
    password: 123456
    jedis:
      pool:
        max-active: 50
        max-idle: 20
        max-wait: 3000
        min-idle: 2
    timeout: 5000
  datasource:
    url: jdbc:mysql://localhost:3306/bilibili?useTimezone=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 6000
      min-evictable-idle-time-millis: 3000
      fiters: stat
      async-init: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.SlowSqlMills=5000
      monitor:
        allow: 127.0.0.1
        loginUsername: admin
        loginPassword: admin
        resetEnable: false
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false # 对于开发，最好禁用缓存
file:
  upload-dir: package